ansible_user: hexly
ansible_python_interpreter: /usr/bin/python3.10
redmine_port: 3000

postgres_vars:
  POSTGRES_USER: "redmine"
  POSTGRES_PASSWORD: "Super-Secret-Redmine-P@ssw0rd!"
  POSTGRES_DB: "redmine"

redmine_vars:
  REDMINE_DB_POSTGRES: "postgres_container"
  REDMINE_DB_USERNAME: "{{ postgres_vars.POSTGRES_USER }}"
  REDMINE_DB_PASSWORD: "{{ postgres_vars.POSTGRES_PASSWORD }}"
  REDMINE_DB_DATABASE: "{{ postgres_vars.POSTGRES_DB }}"